# 가독성을 위해 .properties 에서 .yml 로 변경했습니다.
# .yml 을 쓰는 이유는 계층형식으로 프로젝트를 설정할 수 있으며 덕분에 가독성이 좋아집니다.
spring:
  application:
    name: jslarticle

# mybatis 설정
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml   # 매퍼 XML 파일 위치
  type-aliases-package: com.projects.jslarticle  # 도메인 객체 패키지
  configuration:
    map-underscore-to-camel-case: true           # DB 컬럼명(snake_case) ↔ 자바필드(camelCase) 자동 매핑